Traceback (most recent call last):
  File "main.py", line 76, in <module>
    np.save(output_path + "/mortality/" + core_id, mortality)
  File "/apps/developers/libraries/python-libs/3.1.0/1/python-3.6.5/lib/python3.6/site-packages/numpy-1.12.1-py3.6-linux-x86_64.egg/numpy/lib/npyio.py", line 490, in save
    fid = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: '/nobackup/py13jh/hpc-subgrid-model/phase_space_gen/output_data/lattice/24-07-2019-HPC//mortality/005.npy'
